name: tensor
channels:
  - defaults
  - anaconda
  - conda-forge
  - nodefaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - anyio=3.5.0=py310h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310h7f8727e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=22.1.0=py310h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py310h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotli-python=1.0.9=py310hd8f1fbe_8
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.11.17=py310h06a4308_0
  - cffi=1.15.1=py310h5eee18b_3
  - cftime=1.6.2=py310hde88566_1
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - contourpy=1.0.5=py310hdb19cb5_0
  - cudatoolkit=11.8.0=h4ba93d1_12
  - cudnn=8.9.2.26=cuda11_0
  - curl=8.1.1=h5eee18b_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py310h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.9=h6a678d5_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.1=h52c9d5c_1
  - fonts-conda-forge=1=0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_1
  - glib=2.69.1=he621ea3_2
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.12.1=nompi_h2750804_100
  - icu=58.2=he6710b0_3
  - idna=3.4=py310h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.19.2=py310h2f386ee_0
  - ipython=8.8.0=py310h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py310h06a4308_1
  - jinja2=3.1.2=py310h06a4308_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h7f8727e_0
  - jsonschema=4.16.0=py310h06a4308_0
  - jupyter_client=7.4.8=py310h06a4308_0
  - jupyter_contrib_core=0.4.0=pyhd8ed1ab_0
  - jupyter_contrib_nbextensions=0.7.0=pyhd8ed1ab_0
  - jupyter_core=5.1.1=py310h06a4308_0
  - jupyter_highlight_selected_word=0.2.0=py310hff52083_1005
  - jupyter_latex_envs=1.4.6=pyhd8ed1ab_1002
  - jupyter_nbextensions_configurator=0.6.1=pyhd8ed1ab_0
  - jupyter_server=1.23.4=py310h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - kaleido-core=0.2.1=h3644ca4_0
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.19.4=h568e23c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcblas=3.9.0=12_linux64_mkl
  - libcurl=8.1.1=h91b91d3_0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h516909a_1
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=13.1.0=he5830b7_0
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - liblapack=3.9.0=12_linux64_mkl
  - libllvm10=10.0.1=hbcb73fb_5
  - libnetcdf=4.8.1=nompi_hb3fd0d9_101
  - libnghttp2=1.52.0=ha637b67_1
  - libpng=1.6.37=hbc83047_0
  - libpq=12.9=h16c4e8d_3
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libtiff=4.5.0=h6a678d5_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - libzip=1.8.0=h5cef20c_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lxml=4.9.1=py310h1edc446_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py310h7f8727e_0
  - mathjax=2.7.7=ha770c72_3
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mistune=0.8.4=py310h7f8727e_1000
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - munkres=1.1.4=py_0
  - nbclassic=0.4.8=py310h06a4308_0
  - nbclient=0.5.13=py310h06a4308_0
  - nbconvert=6.5.4=py310h06a4308_0
  - nbformat=5.7.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py310h06a4308_0
  - netcdf4=1.6.0=nompi_py310h947f774_100
  - networkx=3.2=pyhd8ed1ab_1
  - notebook=6.5.2=py310h06a4308_0
  - notebook-shim=0.2.2=py310h06a4308_0
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - openssl=1.1.1w=h7f8727e_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - platformdirs=2.5.2=py310h06a4308_0
  - plotly=5.17.0=pyhd8ed1ab_0
  - ply=3.11=py310h06a4308_0
  - pooch=1.7.0=pyha770c72_3
  - prometheus_client=0.14.1=py310h06a4308_0
  - prompt-toolkit=3.0.36=py310h06a4308_0
  - psutil=5.9.0=py310h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pynndescent=0.5.10=pyh1a96a4e_0
  - pyparsing=3.0.9=py310h06a4308_0
  - pyqt=5.15.7=py310h6a678d5_1
  - pyrsistent=0.18.0=py310h7f8727e_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.9=h7a1cb2a_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py310h06a4308_0
  - python-kaleido=0.2.1=pyhd8ed1ab_0
  - python-louvain=0.16=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2023.3=pyhd8ed1ab_0
  - pyyaml=6.0=py310h5eee18b_1
  - pyzmq=23.2.0=py310h6a678d5_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtwebkit=5.212=h4eab89a_4
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=65.6.3=py310h06a4308_0
  - sip=6.6.2=py310h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py310h06a4308_1
  - soupsieve=2.3.2.post1=py310h06a4308_0
  - sqlite=3.40.1=h5082296_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=8.2.3=pyhd8ed1ab_0
  - terminado=0.17.1=py310h06a4308_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tinycss2=1.2.1=py310h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.2=py310h5eee18b_0
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.7.1=py310h06a4308_0
  - tzdata=2022a=hda174b7_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310h06a4308_1
  - websocket-client=0.58.0=py310h06a4308_4
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - absl-py==1.4.0
      - alembic==1.15.2
      - arviz==0.22.0
      - astunparse==1.6.3
      - cachetools==5.3.1
      - cdsapi==0.7.7
      - cloudpickle==2.2.1
      - colorlog==6.9.0
      - colour==0.1.5
      - cons==0.4.7
      - cvxopt==1.3.0
      - ecmwf-datastores-client==0.4.1
      - etuples==0.3.10
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - gast==0.4.0
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.57.0
      - h5netcdf==1.6.4
      - h5py==3.13.0
      - infomap==2.7.1
      - ipywidgets==8.1.0
      - jupyterlab-widgets==3.0.8
      - keras==3.9.2
      - libclang==16.0.6
      - llvmlite==0.44.0
      - logical-unification==0.4.6
      - mako==1.3.10
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - minikanren==1.0.5
      - ml-dtypes==0.5.1
      - multipledispatch==1.0.0
      - multiurl==0.3.7
      - namex==0.0.8
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cudnn-cu11==8.9.4.25
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - optree==0.15.0
      - optuna==4.2.1
      - optuna-integration==4.2.1
      - packaging==25.0
      - pandas==2.2.3
      - patsy==1.0.1
      - phdu==3.0.3
      - pillow==12.0.0
      - pip==25.0.1
      - protobuf==4.24.4
      - pvlib==0.12.0
      - pyarrow==22.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pygments==2.19.1
      - pymc==5.25.1
      - pyqt5-sip==12.11.0
      - pytensor==2.31.7
      - requests-oauthlib==1.3.1
      - rich==14.0.0
      - rsa==4.9
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - shap==0.47.1
      - slicer==0.0.8
      - sqlalchemy==2.0.40
      - statsmodels==0.14.5
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.19.0
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.33.0
      - termcolor==2.3.0
      - tidypath==1.5.2
      - toolz==1.0.0
      - ttkbootstrap==1.19.2
      - typing-extensions==4.13.1
      - umap-learn==0.5.7
      - urllib3==1.26.16
      - werkzeug==2.3.7
      - widgetsnbextension==4.0.8
      - wrapt==1.15.0
      - xarray==2025.6.1
      - xarray-einstats==0.8.0
      - xgboost==1.7.6
prefix: /home/jorgemedina/anaconda3/envs/tensor
